type IoUserRegistrationState = struct {
  all_users: vec struct { actor_id, str },
};

constructor {
  New : ();
};

service UserRegistration {
  Register : (user_name: str) -> bool;
  query GetUsers : () -> IoUserRegistrationState;
};

